default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: franceforward_development

test:
  <<: *default
  database: franceforward_test

production:
  <<: *default
  database: franceforward_production
  # username: franceforward
  username: gqbxvihzwytjzt
  password: <%= ENV['FRANCEFORWARD_DATABASE_PASSWORD'] %>
